accounts/urls.py
from django.urls import path
from .views import (index, register, login_view, logout_view, profile, edit_profile)

app_name = 'accounts'
urlpatterns = [
    path('', index, name='home'),
    path('register/', register, name='register'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('profile/', profile, name='profile'),
    path('profile/edit/', edit_profile, name='edit_profile'),
]

blog/urls.py
from django.urls import path
from .views import (ArticleView, ArticleDetail)

app_name = 'blog'
urlpatterns = [
    path('articles/', ArticleView.as_view(), name='index'),
    path('articles/<pk>/', ArticleDetail.as_view(), name='article'),
]

health/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('chat/', include('chat.urls')),
    path('blog/', include('blog.urls')),
    path('', include(('events.urls', 'events'), namespace='calendar')),
    path('api/', include('history.api.urls')),
    path('tinymce/', include('tinymce.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Social Authentication urls
urlpatterns += path('oauth/', include('social_django.urls'), name='social_auth'),
urlpatterns += path('api-auth/', include('rest_framework.urls'), name='rest_framework'),

accounts/models.py
from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import User
from django.dispatch import receiver


class UserProfile(models.Model):

    """User profile linked to user via OneToOneField."""
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    id_number = models.IntegerField(blank=False, null=True)
    date_of_birth = models.DateField(blank=False, null=True)
    marital_status = models.CharField(
        choices=(
            ('Single', 'Single'),
            ('Married', 'Married'),
            ('Divorced', 'Divorced'),
            ('Widowed', 'Widowed'),
        ),
        max_length=20, null=True, blank=True
    )
    religion = models.CharField(
        choices=(
            ('Agnostic', 'Agnostic'),
            ('Atheist', 'Atheist'),
            ('Buddhism', 'Buddhism'),
            ('Christianity', 'Christianity'),
            ('Hinduism', 'Hinduism'),
            ('Islam', 'Islam'),
            ('Judaism', 'Judaism'),
            ('Nonreligious', 'Non-religious'),
            ('Rastafarianism', 'Rastafarianism'),
            ('Other', 'Other')
        ),
        max_length=20, null=True, blank=True
    )
    gender = models.CharField(
        choices=(('Male', 'Male'), ('Female', 'Female')),
        max_length=6, null=True, blank=False
    )

    def __str__(self):
        """Return Fullname."""
        full_name = '%s %s' % (self.user.first_name, self.user.last_name)
        return full_name


@receiver(post_save, sender=User)
def create_profile(sender, instance, created, **kwargs):
    """Automatically create a userprofile one a user is created."""
    if created:
        UserProfile.objects.create(user=instance).save()

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfile


def widget_attrs(placeholder):
    return {'class': 'form-control mb-2 mr-md-2', 'placeholder': placeholder}


def form_kwargs(widget, label, max_length):
    return {'widget': widget, 'label': label, 'max_length': max_length}


class RegistrationForm(forms.Form):
    first_name = forms.CharField(
        **form_kwargs(
            widget=forms.TextInput(attrs=widget_attrs('')),
            label='First Name',
            max_length=20
        )
    )
    last_name = forms.CharField(
        **form_kwargs(
            widget=forms.TextInput(attrs=widget_attrs('')),
            label='Last Name',
            max_length=20
        )
    )
    username = forms.CharField(
        **form_kwargs(
            widget=forms.TextInput(attrs=widget_attrs('')),
            label='Phone Number',
            max_length=15
        )
    )
    email = forms.EmailField(
        **form_kwargs(
            widget=forms.TextInput(attrs=widget_attrs('')),
            label='Email',
            max_length=64 + 255
        )
    )
    password = forms.CharField(
        **form_kwargs(
            widget=forms.PasswordInput(attrs=widget_attrs('')),
            label='Password',
            max_length=64
        )
    )
    password_confirmation = forms.CharField(
        **form_kwargs(
            widget=forms.PasswordInput(attrs=widget_attrs('')),
            label='Confirm Password',
            max_length=64
        )
    )

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        password_confirmation = self.cleaned_data.get('password_confirmation')
        # Only accept phone number
        try:
            [int(char) for char in username]
        except Exception:
            raise forms.ValidationError(
                'Your phone number may contain only numbers')

        if len(username) != 10:
            raise forms.ValidationError(
                'Please enter a phone number with 10 digits!')
        # Clean password
        if password != password_confirmation:
            raise forms.ValidationError('Passwords do not match!')

        return self.cleaned_data


class LoginForm(forms.Form):
    username = forms.CharField(
        **form_kwargs(
            widget=forms.TextInput(attrs=widget_attrs('')),
            label='Phone Number',
            max_length=15
        )
    )
    password = forms.CharField(
        **form_kwargs(
            widget=forms.PasswordInput(attrs=widget_attrs('')),
            label='Password',
            max_length=64
        )
    )

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        user = User.objects.filter(username=username).first()
        if not user:
            raise forms.ValidationError('The user is not registered!')
        elif user and not user.check_password(password):
            raise forms.ValidationError('Password Incorrect!')

        return self.cleaned_data


class UserForm(forms.ModelForm):
    class Meta:
        """Model Forms"""
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']
        
    # def clean(self):
    #     username = self.cleaned_data.get('username')
    #     email = self.cleaned_data.get('email')

    #     if email and User.objects.filter(email=email).exclude(username=username).count():
    #         raise forms.ValidationError(
    #             'This email address is already in use. Please supply a different email address.')
    #     return self.cleaned_data


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        exclude = ['user', 'avatar']

    def __init__(self, *args, **kwargs):
        """Customize Model-Form fields."""
        super().__init__(*args, **kwargs)
        self.fields['date_of_birth'].help_text = 'YYYY-MM-DD'

    def clean(self):
        id_number = self.cleaned_data.get('id_number')

        if len(str(id_number)) != 8:
            raise forms.ValidationError(
                'Please enter valid Identification Number!')
        return self.cleaned_data

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .forms import RegistrationForm, LoginForm, UserForm, UserProfileForm


def index(request):
    """Displays the Landing page and other non-app specific pages."""
    return render(request, 'accounts/index.html')


def register(request):
    """Registers new users to the system."""
    logout(request)
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            User.objects.create_user(
                first_name=request.POST['first_name'],
                last_name=request.POST['last_name'],
                username=request.POST['username'],
                email=request.POST['email'],
                password=request.POST['password'],
            )
            messages.success(
                request, 'Account has been created! Please login below...')
            return redirect('accounts:login')
        else:
            return render(request, 'accounts/register.html', {'form': form})
    else:
        return render(request, 'accounts/register.html', {'form': RegistrationForm()})


def login_view(request):
    """Logs returning users into the system."""
    logout(request)
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            user = authenticate(
                username=request.POST['username'],
                password=request.POST['password'],
            )
            if user is not None:
                if user.is_active:
                    login(request, user)
                    messages.success(request, f'Welcome {user.first_name}!')
                    return redirect('accounts:profile')
        else:
            return render(request, 'accounts/login.html', {'form': form})
    else:
        return render(request, 'accounts/login.html', {'form': LoginForm()})
    return redirect('accounts:login')


def logout_view(request):
    """Ends session for logged-in users."""
    logout(request)
    messages.success(request, 'You have been successfully logged out!')
    return redirect('accounts:login')


@login_required(login_url='/login/')
def profile(request):
    """Shows user profile for logged-in users."""
    user = User.objects.get(username=request.user.username)
    return render(request, 'accounts/profile.html', {'user': user})


@login_required(login_url='/login/')
def edit_profile(request):
    """Allows logged-in users to edit their profile info."""
    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = UserProfileForm(request.POST,
                                       instance=request.user.userprofile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Your Profile has been Updated!')
            return redirect('accounts:profile')
    else:
        user_form = UserForm(instance=request.user)
        profile_form = UserProfileForm(instance=request.user.userprofile)
    context = {
        'user_form': user_form,
        'profile_form': profile_form
    }
    return render(request, 'accounts/edit_profile.html', context)

accounts/templates/accounts/edit_profile.html
{% extends 'base.html' %}

{% load static %}

{% load widget_tweaks %}

{% block title %}Edit Profile - {{user.userprofile}} {% endblock title %}

{% block content %}

<section>
    <div class="col-lg-6 mx-auto">
        <h3 class="text-center">Edit Profile</h3>
        <form class="form-group" action="{% url 'accounts:edit_profile' %}" method="POST" novalidate>
            {% csrf_token %}
            {% for hidden_field in user_form.hidden_fields %}
                {{ hidden_field }}
            {% endfor %}
    
            <!-- User form errors -->
            {% if user_form.non_field_errors %}
            <div class="alert alert-danger" role="alert">
                {% for error in user_form.non_field_errors %}
                    {{ error }}
                {% endfor %}
            </div>
            {% endif %}
    
            <!-- Profile form errors -->
            {% if profile_form.non_field_errors %}
            <div class="alert alert-danger" role="alert">
                {% for error in profile_form.non_field_errors %}
                    {{ error }}
                {% endfor %}
            </div>
            {% endif %}
    
            <!-- Forms -->
            <div class="form-group">
                {% if user_form.is_bound %}
                    {% if user_form.username.errors %}
                        {% render_field user_form.username|attr:"readonly:readonly" class="form-control is-invalid" %}
                        <div class="invalid-feedback">
                            {{ user_form.username.errors }}
                        </div>
                    {% else %}
                        {% render_field user_form.username|attr:"readonly:readonly" class="form-control is-valid" %}
                    {% endif %}
                {% else %}
                    {% render_field user_form.username|attr:"readonly:readonly" class="form-control" %}
                {% endif %}
            </div>
    
            <div class="form-group">
                {{user_form.first_name.label_tag|title}}
                {% if user_form.is_bound %}
                    {% if user_form.first_name.errors %}
                        {% render_field user_form.first_name class="form-control is-invalid" %}
                        <div class="invalid-feedback">
                            {{ user_form.first_name.errors }}
                        </div>
                    {% else %}
                        {% render_field user_form.first_name class="form-control is-valid" %}
                    {% endif %}
                {% else %}
                    {% render_field user_form.first_name class="form-control" %}
                {% endif %}
            </div>
    
            <div class="form-group">
                {{user_form.last_name.label_tag|title}}
                {% if user_form.is_bound %}
                    {% if user_form.last_name.errors %}
                        {% render_field user_form.last_name class="form-control is-invalid" %}
                        <div class="invalid-feedback">
                            {{ user_form.last_name.errors }}
                        </div>
                    {% else %}
                        {% render_field user_form.last_name class="form-control is-valid" %}
                    {% endif %}
                {% else %}
                    {% render_field user_form.last_name class="form-control" %}
                {% endif %}
            </div>
    
            <div class="form-group">
                {{user_form.email.label_tag|title}}
                {% if user_form.is_bound %}
                    {% if user_form.email.errors %}
                        {% render_field user_form.email class="form-control is-invalid" %}
                        <div class="invalid-feedback">
                            {{ user_form.email.errors }}
                        </div>
                    {% else %}
                        {% render_field user_form.email class="form-control is-valid" %}
                    {% endif %}
                {% else %}
                    {% render_field user_form.email class="form-control" %}
                {% endif %}
            </div>
    
            {% for field in profile_form.visible_fields %}
            <div class="form-group">
                {{field.label_tag|title}}
                {% if profile_form.is_bound %}
                    {% if field.errors %}
                        {% render_field field class="form-control is-invalid" %}
                        {% for error in field.errors %}
                        <div class="invalid-feedback">
                            {{ error }}
                        </div>
                        {% endfor %}
                    {% else %}
                        {% render_field field class="form-control is-valid" %}
                    {% endif %}
                {% else %}
                    {% render_field field class="form-control" %}
                {% endif %}
                {% if field.help_text %}
                    <small class="form-text text-muted">{{ field.help_text }}</small>
                {% endif %}
            </div>
            {% endfor %}
            <button type="submit" class="btn btn-sm btn-outline-primary mb-4 float-right">Update</button>
        </form>
    </div>    
</section>

{% endblock content %}

accounts/templates/accounts/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Community Health - Home{% endblock title %}

{% block content %}

<!-- Header Section -->
<header class=text-white">
    <div class="text-center">
        <img src="{% static 'site/images/logos/health_bg.png' %}" class="img-fluid" alt="Responsive image">
        <p class="container"> “Access to good healthcare should not depend on who you are, what you do or where you
            live”
        </p>
    </div>
</header>

<!-- Services Section -->
<section id="services" class="bg-light">
    <div class="container">
        <div class="mx-auto text-center">
            <h2>Our Services</h2>
            <p>Consult a Community Health Medical Practitioner or make an appointment with your nearest Community Health
                Facility.</p>
        </div>
        <div class="row">
            <div class="col-sm-6 text-center">
                <h5> <b>Consult from Home</b> </h5>
                <i class="fas fa-home"></i>
                <p>
                    Teleconsult our medical officers at home. Choose the first available community health officer or
                    choose a
                    specific one to talk to online.
                </p>
            </div>
            <div class="col-sm-6 text-center">
                <h5> <b>Make an Appointment</b> </h5>
                <i class="fas fa-calendar-plus"></i>
                <p>
                    Schedule an in-person appointment with your nearest community health facility from home so you don't
                    have to
                    wait in line.
                </p>
            </div>
        </div>
    </div>
</section>

<!-- About Section -->
<section id="about">
    <div class="container text-white">
        <div class="row">
            <div class="col-sm-6">
                <h5>
                    <p>About Us</p>
                </h5>
                <p>
                    This application is built to allow community health workers and public health officers to carry out
                    their
                    roles more effectively. It ensures a better communitcation channel between registered community
                    health
                    institutions and members of the community.
                </p>
                <p>
                    The platform also serves to inform its user through the blog/news feature which focuses on
                    healthcare and
                    healthy living.
                </p>
            </div>
            <div class="col-sm-3">
                <h5>
                    <p>Vision</p>
                </h5>
                <p>To create community-centric, self-sustaining digital healthcare services.</p>
            </div>
            <div class="col-sm-3">
                <h5>
                    <p>Mission</p>
                </h5>
                <p>To create a community model for improving access and delivery of healthcare services according to
                    society
                    needs.</p>
            </div>
        </div>
    </div>
</section>

{% endblock content %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block title %}Login to your account{% endblock title %}

{% block content %}

<section>
    <div class="col-lg-6 mx-auto">
        <h3 class="text-center">Login</h3>
        <form class="form-group" action="{% url 'accounts:login' %}" method="post" novalidate>
            {% csrf_token %}
            {{message}}
            {% for hidden_field in form.hidden_fields %}
                {{ hidden_field }}
            {% endfor %}
    
            {% if form.non_field_errors %}
            <div class="alert alert-danger" role="alert">
                {% for error in form.non_field_errors %}
                    {{ error }}
                {% endfor %}
            </div>
            {% endif %}
            {% for field in form.visible_fields %}
            <div class="form-group">
                {{ field.label_tag }}
                {% if form.is_bound %}
                    {% if field.errors %}
                        {% render_field field class="form-control is-invalid" %}
                            {% for error in field.errors %}
                            <div class="invalid-feedback">
                                {{ error }}
                            </div>
                            {% endfor %}
                    {% else %}
                        {% render_field field class="form-control is-valid" %}
                    {% endif %}
                {% else %}
                    {% render_field field class="form-control" %}
                {% endif %}
                {% if field.help_text %}
                    <small class="form-text text-muted">{{ field.help_text }}</small>
                {% endif %}
            </div>
            {% endfor %}
            <div class="text-center">
            <button type="submit" class="btn btn-sm btn-outline-primary float-left">Login</button>
                <!-- Continue with -->
                <a href="{% url 'social:begin' 'facebook' %}" class="float-right">
                    <img src="{% static 'accounts/images/facebook_continue.png' %}" alt="" width="190" height="30.89">
                </a>
                <br> <br>
                <hr>
                Don't have an account yet? <a href="{% url 'accounts:register' %}" class="custom-link">Register Here</a>
            </div>
    
        </form>
    </div>
</section>

{% endblock content %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load static %}

{% block title %} Profile - {{user.userprofile}} {% endblock title %}

{% block content %}

<section>
    <div class="col-lg-8 mx-auto">
        <h3>Profile</h3>
        <div class="card mt-4">
            <div class="card-body">
                <div class="row">
                    <div class="col-sm-6">
                        {% if user.userprofile.avatar %}
                        <img src="{{user.userprofile.avatar.url}}" class="rounded-circle"
                            alt="Profile photo of {{user.userprofile}}" width="80" height="80"
                            style="border: 1px solid #0c6985;">
                        {% else %}
                        <img src="{% static 'accounts/images/default_avatar.svg' %}" class="rounded-circle"
                            alt="default avatar" width="80" height="80" style="border: 1px solid #0c6985;">
                        {% endif %}
                    </div>
                    <div class="col-sm-6  pt-3">
                        <h5 class="card-title"> {{user.userprofile}} </h5>
                        <p>{{user.email}}</p>
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-sm-6">
                        <div>
                            <b>Phone Number</b>
                            <p>{{user}}</p>
                        </div>
                        <div>
                            <b>Date Joined</b>
                            <p>{{user.date_joined|date:"M. d, Y"}}</p>
                        </div>
                        <div>
                            <b>User ID</b>
                            <p>{{user.id}}</p>
                        </div>
                        <div>
                            <b>ID Number</b>
                            <p>{{user.userprofile.id_number}}</p>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div>
                            <b>Date of Birth</b>
                            <p>{{user.userprofile.date_of_birth}}</p>
                        </div>
                        <div>
                            <b>Gender</b>
                            <p>{{user.userprofile.gender}}</p>
                        </div>
                        <div>
                            <b>Marital Status</b>
                            <p>{{user.userprofile.marital_status}}</p>
                        </div>
                        <div>
                            <b>Religion</b>
                            <p>{{user.userprofile.religion}}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <a href="{% url 'accounts:edit_profile' %}">
            <button class="btn btn-sm btn-outline-primary mb-4 mt-4">Edit Profile</button>
        </a>
        <h3>User Information</h3>
        <div class="card mt-4">
            <div class="card-body">
                <div class="row">
                    <div class="col-sm-6">
                        <div>
                            <b>User ID</b>
                            <p>{{user.id}}</p>
                        </div>
                        <div>
                            <b>User Permissions</b>
                            <p>{{user.}}</p>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div>
                            <b>Last Login</b>
                            <p>{{user.last_login}}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <a href=" {% url 'admin:password_change' %} ">
            <button class="btn btn-sm btn-outline-primary mb-4 mt-4">Change Password</button>
        </a>
    </div>
</section>

{% endblock content %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}

{% load static %}

{% load widget_tweaks %}

{% block title %}Register to Join Us{% endblock title %}

{% block content %}

<section>
    <div class="col-lg-6 mx-auto">
        <h3 class="text-center">Register</h3>
        <form class="form-group" action="{% url 'accounts:register' %}" method="post" novalidate>
            {% csrf_token %}
            {% for hidden_field in form.hidden_fields %}
                {{ hidden_field }}
            {% endfor %}
    
            {% if form.non_field_errors %}
            <div class="alert alert-danger" role="alert">
                {% for error in form.non_field_errors %}
                    {{ error }}
                {% endfor %}
            </div>
            {% endif %}
            {% for field in form.visible_fields %}
            <div class="form-group">
                {{field.label_tag}}
                {% if form.is_bound %}
                    {% if field.errors %}
                        {% render_field field class="form-control is-invalid" %}
                        {% for error in field.errors %}
                        <div class="invalid-feedback">
                            {{ error }}
                        </div>
                        {% endfor %}
                    {% else %}
                        {% render_field field class="form-control is-valid" %}
                    {% endif %}
                {% else %}
                    {% render_field field class="form-control" %}
                {% endif %}
                {% if field.help_text %}
                    <small class="form-text text-muted">{{ field.help_text }}</small>
                {% endif %}
            </div>
            {% endfor %}
            <button type="submit" class="btn btn-outline-primary mb-4 ">Register</button><br>
            Already have an account? <a href="{% url 'accounts:login' %}" class="custom-link">Login Here</a>
        </form>
    </div>
</section>

{% endblock content %}