blog/urls.py
from django.urls import path
from .views import (ArticleView, ArticleDetail)

app_name = 'blog'
urlpatterns = [
    path('articles/', ArticleView.as_view(), name='index'),
    path('articles/<pk>/', ArticleDetail.as_view(), name='article'),
]

health/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('chat/', include('chat.urls')),
    path('blog/', include('blog.urls')),
    path('', include(('events.urls', 'events'), namespace='calendar')),
    path('api/', include('history.api.urls')),
    path('tinymce/', include('tinymce.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Social Authentication urls
urlpatterns += path('oauth/', include('social_django.urls'), name='social_auth'),
urlpatterns += path('api-auth/', include('rest_framework.urls'), name='rest_framework'),

blog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from tinymce import HTMLField
from autoslug import AutoSlugField


class Category(models.Model):
    """Blog Post Categories."""
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Article(models.Model):
    """Blog Article posted by signed-in users."""
    author = models.ForeignKey(User, on_delete=models.PROTECT)
    title = models.CharField(max_length=100, blank=False)
    headline = models.CharField(max_length=255, blank=False)
    pub_date = models.DateTimeField(auto_now_add=True)
    slug = AutoSlugField(populate_from='title', unique_with='pub_date__month')
    category = models.ManyToManyField(Category, default="General")
    body = HTMLField('Body Content')
    publish = models.BooleanField(default=False)

    class Meta:
        ordering = ['-pub_date', 'author', 'publish']

    def __str__(self):
        return self.title

blog/views.py
from django.views.generic import ListView, DetailView
from .models import Article, Category


class ArticleView(ListView):
    """Shows a list and summary of all blogs."""
    queryset = Article.objects.order_by('-pub_date')
    template_name = 'blog/index.html'
    paginate_by = 3


class ArticleDetail(DetailView):
    """Displays individual blog posts/articles."""
    model = Article
    template_name = 'blog/article.html'

blog/templates/blog/article.html
{% extends 'base.html' %}
{% load static %}

{% block title %} {{object.title}} - {{object.author.userprofile}} {% endblock %}
{% block css %}
<link rel="stylesheet" href="{% static 'blog/css/style.css' %}"> 
{% endblock %}

{% block content %}

<section id="article">
	<div class="container">
		<div class="row">
			<div class="col-lg-10 mx-auto">
				<div class="card">
					<div class="card-body">
						<h1 class="card-title"> {{object.title|title}} </h1>
						<div class="row">
							<div class="col">
								<small> By {{object.author.userprofile}} </small>
							</div>
							<div class="col">
								<small class="float-right"> Published on {{object.pub_date}} </small>
							</div>
						</div>
						<hr>
						<p class="text-muted"> {{object.headline}} </p>
						{{object.slug}}
						<p class="card-text"> {{object.body|safe}} </p>
						<hr>
						<!-- Pending Query. Needs to be fixed! -->
						<h5> Categories </h5>
						{% for cat in object.category.values_list %}
						<a href="#" class="badge badge-dark"> {{ cat}} </a>
						{% endfor %}
						<!-- --- -->
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

{% endblock %}

blog/templates/blog/index.html
{% extends 'base.html' %}
{% load humanize %}
{% load static %}

{% block title %} Health Blog Posts Page {% endblock %}
{% block css %} <link rel="stylesheet" href="{% static 'blog/css/style.css' %}"> {% endblock %}

{% block content %}

<section id="article_list">
	<div class="container">
		<h3>Health Blog Posts</h3>
		<ol class="list-group">
		{% if user.is_authenticated %}
			<li class="list-group-item">
				<a href="/admin/blog/article/add/"> 
					<button class="btn btn-primary">New Article</button>
				</a>
			</li>
		{% endif %}
			{% for object in object_list %}
			<li class="list-group-item">
				<a href="{% url 'blog:article' object.id %}"> {{object.title}} </a>
				<p> {{object.headline|slice:":125"}}..... </p>
			</li>
			{% endfor %}
		</ol>
	</div>
</section>

{% if is_paginated %}
<nav aria-label="Page navigation">
	<ul class="pagination justify-content-center">
		{% if page_obj.has_previous %}
		<li class="page-item">
			<a class="page-link" href="?page=1" aria-label="Previous">
				<span aria-hidden="true">Latest</span>
			</a>
		</li>
		<li class="page-item">
			<a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
				<span aria-hidden="true">&laquo;</span>
			</a>
		</li>
		{% endif %}

		{% for i in paginator.page_range %}
		{% if page_obj.number == i %}
		<li class="page-item active"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
		{% else %}
		<li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
		{% endif %}
		{% endfor %}

		{% if page_obj.has_next %}
		<li class="page-item">
			<a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
				<span aria-hidden="true">&raquo;</span>
			</a>
		</li>
		<li class="page-item">
			<a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Last">
				<span aria-hidden="true">Old</span>
			</a>
		</li>
		{% endif %}
	</ul>
</nav>
{% endif %}

{% endblock %}