accounts/urls.py
from django.urls import path
from .views import (index, register, login_view, logout_view, profile, edit_profile)

app_name = 'accounts'
urlpatterns = [
    path('', index, name='home'),
    path('register/', register, name='register'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('profile/', profile, name='profile'),
    path('profile/edit/', edit_profile, name='edit_profile'),
]

blog/urls.py
from django.urls import path
from .views import (ArticleView, ArticleDetail)

app_name = 'blog'
urlpatterns = [
    path('articles/', ArticleView.as_view(), name='index'),
    path('articles/<pk>/', ArticleDetail.as_view(), name='article'),
]

chat/urls.py
from django.urls import path
from .views import (index, room)

app_name = 'chat'
urlpatterns = [
    path('', index, name='index'),
    path('<str:room_name>/', room, name='room'),
]

events/urls.py
from __future__ import unicode_literals
from django.urls import re_path
from . import views


app_name = 'events'
urlpatterns = [
    re_path(r'^event$', views.EventMonthView.as_view(), name='index'),
    re_path(r'^create$', views.CreateEvent.as_view(), name='create'),
    re_path(r'^month/shift$', views.EventMonthView.as_view(), name='month_shift'),
    re_path(r'^event-list/shift$', views.EventMonthView.as_view(), name='event_list_shift'),
    re_path(r'^cal-and-list/shift$', views.EventMonthView.as_view(), name='cal_and_list_shift'),
    re_path(r'^event/(?P<pk>[\w-]+)$', views.EventDetailView.as_view(), name='detail'),
    re_path(r'^(?P<year>\d{4})/(?P<month>\d{2}|\d)$', views.EventMonthView.as_view(), name='list'),
    re_path(r'^(?P<year>\d{4})/(?P<month>\d{2}|\d)/(?P<day>\d{2}|\d)$', views.EventDayView.as_view(), name='day_list'),
]

health/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('chat/', include('chat.urls')),
    path('blog/', include('blog.urls')),
    path('', include(('events.urls', 'events'), namespace='calendar')),
    path('api/', include('history.api.urls')),
    path('tinymce/', include('tinymce.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Social Authentication urls
urlpatterns += path('oauth/', include('social_django.urls'), name='social_auth'),
urlpatterns += path('api-auth/', include('rest_framework.urls'), name='rest_framework'),

accounts/models.py
from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import User
from django.dispatch import receiver


class UserProfile(models.Model):

    """User profile linked to user via OneToOneField."""
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    id_number = models.IntegerField(blank=False, null=True)
    date_of_birth = models.DateField(blank=False, null=True)
    marital_status = models.CharField(
        choices=(
            ('Single', 'Single'),
            ('Married', 'Married'),
            ('Divorced', 'Divorced'),
            ('Widowed', 'Widowed'),
        ),
        max_length=20, null=True, blank=True
    )
    religion = models.CharField(
        choices=(
            ('Agnostic', 'Agnostic'),
            ('Atheist', 'Atheist'),
            ('Buddhism', 'Buddhism'),
            ('Christianity', 'Christianity'),
            ('Hinduism', 'Hinduism'),
            ('Islam', 'Islam'),
            ('Judaism', 'Judaism'),
            ('Nonreligious', 'Non-religious'),
            ('Rastafarianism', 'Rastafarianism'),
            ('Other', 'Other')
        ),
        max_length=20, null=True, blank=True
    )
    gender = models.CharField(
        choices=(('Male', 'Male'), ('Female', 'Female')),
        max_length=6, null=True, blank=False
    )

    def __str__(self):
        """Return Fullname."""
        full_name = '%s %s' % (self.user.first_name, self.user.last_name)
        return full_name


@receiver(post_save, sender=User)
def create_profile(sender, instance, created, **kwargs):
    """Automatically create a userprofile one a user is created."""
    if created:
        UserProfile.objects.create(user=instance).save()

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfile


def widget_attrs(placeholder):
    return {'class': 'form-control mb-2 mr-md-2', 'placeholder': placeholder}


def form_kwargs(widget, label, max_length):
    return {'widget': widget, 'label': label, 'max_length': max_length}


class RegistrationForm(forms.Form):
    first_name = forms.CharField(
        **form_kwargs(
            widget=forms.TextInput(attrs=widget_attrs('')),
            label='First Name',
            max_length=20
        )
    )
    last_name = forms.CharField(
        **form_kwargs(
            widget=forms.TextInput(attrs=widget_attrs('')),
            label='Last Name',
            max_length=20
        )
    )
    username = forms.CharField(
        **form_kwargs(
            widget=forms.TextInput(attrs=widget_attrs('')),
            label='Phone Number',
            max_length=15
        )
    )
    email = forms.EmailField(
        **form_kwargs(
            widget=forms.TextInput(attrs=widget_attrs('')),
            label='Email',
            max_length=64 + 255
        )
    )
    password = forms.CharField(
        **form_kwargs(
            widget=forms.PasswordInput(attrs=widget_attrs('')),
            label='Password',
            max_length=64
        )
    )
    password_confirmation = forms.CharField(
        **form_kwargs(
            widget=forms.PasswordInput(attrs=widget_attrs('')),
            label='Confirm Password',
            max_length=64
        )
    )

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        password_confirmation = self.cleaned_data.get('password_confirmation')
        # Only accept phone number
        try:
            [int(char) for char in username]
        except Exception:
            raise forms.ValidationError(
                'Your phone number may contain only numbers')

        if len(username) != 10:
            raise forms.ValidationError(
                'Please enter a phone number with 10 digits!')
        # Clean password
        if password != password_confirmation:
            raise forms.ValidationError('Passwords do not match!')

        return self.cleaned_data


class LoginForm(forms.Form):
    username = forms.CharField(
        **form_kwargs(
            widget=forms.TextInput(attrs=widget_attrs('')),
            label='Phone Number',
            max_length=15
        )
    )
    password = forms.CharField(
        **form_kwargs(
            widget=forms.PasswordInput(attrs=widget_attrs('')),
            label='Password',
            max_length=64
        )
    )

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        user = User.objects.filter(username=username).first()
        if not user:
            raise forms.ValidationError('The user is not registered!')
        elif user and not user.check_password(password):
            raise forms.ValidationError('Password Incorrect!')

        return self.cleaned_data


class UserForm(forms.ModelForm):
    class Meta:
        """Model Forms"""
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']
        
    # def clean(self):
    #     username = self.cleaned_data.get('username')
    #     email = self.cleaned_data.get('email')

    #     if email and User.objects.filter(email=email).exclude(username=username).count():
    #         raise forms.ValidationError(
    #             'This email address is already in use. Please supply a different email address.')
    #     return self.cleaned_data


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        exclude = ['user', 'avatar']

    def __init__(self, *args, **kwargs):
        """Customize Model-Form fields."""
        super().__init__(*args, **kwargs)
        self.fields['date_of_birth'].help_text = 'YYYY-MM-DD'

    def clean(self):
        id_number = self.cleaned_data.get('id_number')

        if len(str(id_number)) != 8:
            raise forms.ValidationError(
                'Please enter valid Identification Number!')
        return self.cleaned_data

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .forms import RegistrationForm, LoginForm, UserForm, UserProfileForm


def index(request):
    """Displays the Landing page and other non-app specific pages."""
    return render(request, 'accounts/index.html')


def register(request):
    """Registers new users to the system."""
    logout(request)
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            User.objects.create_user(
                first_name=request.POST['first_name'],
                last_name=request.POST['last_name'],
                username=request.POST['username'],
                email=request.POST['email'],
                password=request.POST['password'],
            )
            messages.success(
                request, 'Account has been created! Please login below...')
            return redirect('accounts:login')
        else:
            return render(request, 'accounts/register.html', {'form': form})
    else:
        return render(request, 'accounts/register.html', {'form': RegistrationForm()})


def login_view(request):
    """Logs returning users into the system."""
    logout(request)
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            user = authenticate(
                username=request.POST['username'],
                password=request.POST['password'],
            )
            if user is not None:
                if user.is_active:
                    login(request, user)
                    messages.success(request, f'Welcome {user.first_name}!')
                    return redirect('accounts:profile')
        else:
            return render(request, 'accounts/login.html', {'form': form})
    else:
        return render(request, 'accounts/login.html', {'form': LoginForm()})
    return redirect('accounts:login')


def logout_view(request):
    """Ends session for logged-in users."""
    logout(request)
    messages.success(request, 'You have been successfully logged out!')
    return redirect('accounts:login')


@login_required(login_url='/login/')
def profile(request):
    """Shows user profile for logged-in users."""
    user = User.objects.get(username=request.user.username)
    return render(request, 'accounts/profile.html', {'user': user})


@login_required(login_url='/login/')
def edit_profile(request):
    """Allows logged-in users to edit their profile info."""
    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = UserProfileForm(request.POST,
                                       instance=request.user.userprofile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Your Profile has been Updated!')
            return redirect('accounts:profile')
    else:
        user_form = UserForm(instance=request.user)
        profile_form = UserProfileForm(instance=request.user.userprofile)
    context = {
        'user_form': user_form,
        'profile_form': profile_form
    }
    return render(request, 'accounts/edit_profile.html', context)

accounts/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title> {% block title %}{% endblock %} </title>

  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  <!-- Custom CSS -->
  <link rel="stylesheet" href="{% static 'site/css/style.css' %}">
  <link rel="stylesheet" href="{% static 'accounts/css/style.css' %}">
  {% block css %}{% endblock %}
  <!-- Fontawesome Kit -->
  <script src="https://kit.fontawesome.com/b1eb41e9a4.js" crossorigin="anonymous"></script>
  <!-- Favicons -->
  <link rel="apple-touch-icon" sizes="180x180" href="{% static 'site/images/favicons/apple-touch-icon.png' %}">
  <link rel="icon" type="image/png" sizes="32x32" href="{% static 'site/images/favicons/favicon-32x32.png' %}">
  <link rel="icon" type="image/png" sizes="16x16" href="{% static 'site/images/favicons/favicon-16x16.png' %}">
  <link rel="manifest" href="{% static 'site/images/favicons/site.webmanifest' %}">
  <link rel="shortcut icon" href="{% static 'site/images/favicons/favicon.ico' %}" type="image/x-icon">

</head>

<body id="page-top">

  <!-- Navigation Bar -->
  <nav class="navbar navbar-expand-lg navbar-light bg-light shadow fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand js-scroll-trigger" href="/#page-top">
        <img src="{% static 'site/images/logos/health_no_bg.png' %}" width="50" height="50" class="d-inline-block"
          alt="">
        Community Health
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
        aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse text-center" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="/#services">Services</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="/#about">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="{% url 'chat:index' %}">Chat</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="{% url 'events:index' %}">Events</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="{% url 'blog:index' %}">Blog</a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item dropdown">
            <a class="nav-link far fa-user" href="#" id="navbarDropdownMenuLink" role="button"
              data-toggle="dropdown" aria-haspopup="false" aria-expanded="true">
              {{user.first_name}}
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="/api/" target="_blank" >Rest API</a>
              <a class="dropdown-item" href=" {% url 'accounts:profile' %} ">Profile</a>
              <a class="dropdown-item" href=" {% url 'admin:password_change' %} ">Change Password</a>
              <a class="dropdown-item" href=" {% url 'accounts:logout' %} ">Logout</a>
            </div>
          </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href=" {% url 'accounts:login' %} ">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href=" {% url 'accounts:register' %} ">Register</a>
            </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
  <div style="min-height: 93vh;">
    {% block content %}{% endblock %}
  </div>
<!-- Start of LiveChat (www.livechatinc.com) code -->
<script>
    window.__lc = window.__lc || {};
    window.__lc.license = 12294231;
    ;(function(n,t,c){function i(n){return e._h?e._h.apply(null,n):e._q.push(n)}var e={_q:[],_h:null,_v:"2.0",on:function(){i(["on",c.call(arguments)])},once:function(){i(["once",c.call(arguments)])},off:function(){i(["off",c.call(arguments)])},get:function(){if(!e._h)throw new Error("[LiveChatWidget] You can't use getters before load.");return i(["get",c.call(arguments)])},call:function(){i(["call",c.call(arguments)])},init:function(){var n=t.createElement("script");n.async=!0,n.type="text/javascript",n.src="https://cdn.livechatinc.com/tracking.js",t.head.appendChild(n)}};!n.__lc.asyncInit&&e.init(),n.LiveChatWidget=n.LiveChatWidget||e}(window,document,[].slice))
</script>
<noscript><a href="https://www.livechatinc.com/chat-with/12294231/" rel="nofollow">Chat with us</a>, powered by <a href="https://www.livechatinc.com/?welcome" rel="noopener nofollow" target="_blank">LiveChat</a></noscript>
<!-- End of LiveChat code -->

  <!-- Footer Section -->
  <footer class="pb-1 pt-3">
    <div class="container text-white">
      <p class="text-center">Copyright &copy; {% now "Y" %} | Community Health Management System</p>
    </div>
  </footer>

  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.5.1.min.js"
    integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
    integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous">
  </script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
    integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous">
  </script>

  <!-- Plugin JavaScript -->
  <script src="{% static 'site/js/jquery.easing.min.js' %}"></script>

  <!-- Custom JavaScript for this theme -->
  <script src="{% static 'site/js/script.js' %}"></script>

</body>

</html>